Connecting the bookstore to the API
butlermuwo/bookstore pull request #3
Opened 2022-03-04 13:56 UTC by butlermuwo

## Connecting the bookstore to the API
In this pull request I did the following:

- Read the [Bookstore API documentation](https://www.notion.so/Bookstore-API-51ea269061f849118c65c0a53e88a739) to learn how to use the API.
- Refactored my add book and remove book features to persist changes in the server.
- The Add book and remove book works in the same way after the refactoring.

2022-03-04 15:42 UTC, moise10r requested changes
### Hi **@butlermuwo,**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- Descriptive README file.  ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @moise10r when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-04 15:42 UTC, moise10r commented on src/api/api.js
> +};
- [ ] After cloning your project in my local machine and running `npm install` then `npm run start` I've noticed that the `delete` button does not remove the create book, kindly fix this

2022-03-04 15:42 UTC, moise10r commented on src/components/Bookcard.js
>                <p className="book-category">Science Fiction</p>
- [ ] I have also noticed that any category I select, only created a book with `Science Fiction` category which is set as the default value. kindly fix this and make your book be created with the selected category instead of the `Science Fiction`  as a category

2022-03-05 00:10 UTC, omar-labana commented
# **Approved ✔️**

Hi @butlermuwo,

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-14 12:55 UTC, merged